# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1203d4824cc4dd432323055f94709ce0faa7402318c5f2cf2fbff1655ad0ece9204981ec5331aea3edd94770a9ca0e1fa8ed82061c0011d2c00ff9153485a383

test:
  secret_key_base: 782da7249bcc6fb8535f5c468cae3f9f5a9f6cbf2955c39acfa9aa2bab05b15019fb3792bb3db7f270637aa378edc03969aa45eb4e5fbb66ae95f52591a146de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
